rpc:
  name: easy-rpc
  version: 1.0.1
  serverPort: 9000
  mock: false
  registryConfig:
#    registry: zookeeper
    registry: etcd
#    address: http://localhost:2181
    address: http://localhost:2380